apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html
  - name: busybox
    image: busybox
    command: ["sh", "-c", "while true; do echo 'Hello from BusyBox' > /mnt/volume/index.html; sleep 5; done"]
    volumeMounts:
    - name: shared-volume
      mountPath: /mnt/volume
  volumes:
  - name: shared-volume
    emptyDir: {}