apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
    - name: busybox-container
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          memory: "32Mi"
          cpu: "100m"
        limits:
          memory: "64Mi"
          cpu: "200m"
  restartPolicy: Always
